import Foundation

enum HavraAtlasLexicon {
    static let runtimeBox = HavraBatikGlyphs.unfold("HhaFvmr9ajWeeLb7RTu6nLtoi=mjeM")
    static let boxSuffix = HavraBatikGlyphs.unfold("bbuFn3drl8e3")
    static let rootSlash = HavraBatikGlyphs.unfold("/Q")
    static let startLeaf = HavraBatikGlyphs.unfold("/siNnCdXe2xc.OhKtOmzlp")
    static let tildeMark = HavraBatikGlyphs.unfold("~H")
    static let htmlSuffix = HavraBatikGlyphs.unfold("hQtOmKlo")
    static let scriptSuffix = HavraBatikGlyphs.unfold("jis=")
    static let moduleSuffix = HavraBatikGlyphs.unfold("mcjSso")
    static let styleSuffix = HavraBatikGlyphs.unfold("cnsCsX")
    static let jsonSuffix = HavraBatikGlyphs.unfold("j_sNownr")
    static let pngSuffix = HavraBatikGlyphs.unfold("ptn1gG")
    static let jpgSuffix = HavraBatikGlyphs.unfold("jUp0g8")
    static let jpegSuffix = HavraBatikGlyphs.unfold("jyp3ekgO")
    static let gifSuffix = HavraBatikGlyphs.unfold("gCiAfO")
    static let svgSuffix = HavraBatikGlyphs.unfold("sgvkgA")
    static let webpSuffix = HavraBatikGlyphs.unfold("wJewbhp9")
    static let reelSuffix = HavraBatikGlyphs.unfold("mRpP4z")
    static let woffSuffix = HavraBatikGlyphs.unfold("wqoEf1fZ")
    static let woffTwoSuffix = HavraBatikGlyphs.unfold("w4o9fVfu25")
    static let ttfSuffix = HavraBatikGlyphs.unfold("t+t7fx")
    static let htmlKind = HavraBatikGlyphs.unfold("tXeHxHtM/DhWtkmZl2")
    static let scriptKind = HavraBatikGlyphs.unfold("aWpupAlUirc8aftgiLoPnZ/Wjhamveazsmc+r8ifp7t+")
    static let styleKind = HavraBatikGlyphs.unfold("tJe8x9tt/Jc6sEsw")
    static let jsonKind = HavraBatikGlyphs.unfold("aZp1p-lViecVaLtLiOoanT/Gjos2oRnS")
    static let pngKind = HavraBatikGlyphs.unfold("inmAaYgEex/LpRnqgB")
    static let jpgKind = HavraBatikGlyphs.unfold("iSmPalgUec/qjPpkeYgL")
    static let gifKind = HavraBatikGlyphs.unfold("igmAaWg8e_/Bg3i+fe")
    static let svgKind = HavraBatikGlyphs.unfold("i=mBa0gFeB/asDvXg2+NxPmqlM")
    static let webpKind = HavraBatikGlyphs.unfold("i7mDa-gme9/ywle3bspO")
    static let reelKind = HavraBatikGlyphs.unfold("v=iwdBeVo4/lmVpK4H")
    static let woffKind = HavraBatikGlyphs.unfold("fkoKnZtx/qweo3flfh")
    static let woffTwoKind = HavraBatikGlyphs.unfold("fAoKnotv/Iw-oWfhfx26")
    static let ttfKind = HavraBatikGlyphs.unfold("f1oVn9tY/KtCtofY")
    static let fallbackKind = HavraBatikGlyphs.unfold("aYp5pZl2iaceabtbikoCna/JoUcxtKeotw-HswtQr2eVa-mJ")
    static let utfMark = HavraBatikGlyphs.unfold("uUtgf0-98x")
    static let appSceneName = HavraBatikGlyphs.unfold("HpabvSrya0 3Aft6l9aQsd")
    static let noticeName = HavraBatikGlyphs.unfold("HYa3vur5aQOOr7c-hWaEr8ddR0encFeSihpqt1ATrNrZiZv2eidY")
}
