import Foundation

enum HavraAtlasLexicon {
    static let morningMarketRhythm = HavraBatikGlyphs.unfold("bqaznkarntamFnrpixtytaecrdSetfaglhlj")
    static let ferryHarborRoute = HavraBatikGlyphs.unfold("bbuFn3drl8e3")
    static let familyTableRitual = HavraBatikGlyphs.unfold("/Q")
    static let neighborhoodGameDay = HavraBatikGlyphs.unfold("/siNnCdXe2xc.OhKtOmzlp")
    static let festivalLanternGlow = HavraBatikGlyphs.unfold("~H")
    static let ordinaryCityDay = HavraBatikGlyphs.unfold("hQtOmKlo")
    static let riverMarketMorning = HavraBatikGlyphs.unfold("jis=")
    static let coastalKitchenScene = HavraBatikGlyphs.unfold("mcjSso")
    static let monsoonStreetWalk = HavraBatikGlyphs.unfold("cnsCsX")
    static let bambooLanternPath = HavraBatikGlyphs.unfold("j_sNownr")
    static let spiceAlleyMap = HavraBatikGlyphs.unfold("ptn1gG")
    static let tropicalCourtyardLife = HavraBatikGlyphs.unfold("jUp0g8")
    static let wetMarketTexture = HavraBatikGlyphs.unfold("jyp3ekgO")
    static let templeBellMorning = HavraBatikGlyphs.unfold("gCiAfO")
    static let islandFerryRoute = HavraBatikGlyphs.unfold("sgvkgA")
    static let cityBalconyRoutine = HavraBatikGlyphs.unfold("wJewbhp9")
    static let nightBazaarGlow = HavraBatikGlyphs.unfold("mRpP4z")
    static let streetFoodTrail = HavraBatikGlyphs.unfold("wqoEf1fZ")
    static let craftLaneDetail = HavraBatikGlyphs.unfold("w4o9fVfu25")
    static let fabricMarketPalette = HavraBatikGlyphs.unfold("t+t7fx")
    static let monsoonWindowMood = HavraBatikGlyphs.unfold("tXeHxHtM/DhWtkmZl2")
    static let orchidStallStudy = HavraBatikGlyphs.unfold("aWpupAlUirc8aftgiLoPnZ/Wjhamveazsmc+r8ifp7t+")
    static let harborSeatView = HavraBatikGlyphs.unfold("tJe8x9tt/Jc6sEsw")
    static let penangCraftCorner = HavraBatikGlyphs.unfold("aZp1p-lViecVaLtLiOoanT/Gjos2oRnS")
    static let hanoiLunchStall = HavraBatikGlyphs.unfold("inmAaYgEex/LpRnqgB")
    static let bangkokLaneGuide = HavraBatikGlyphs.unfold("iSmPalgUec/qjPpkeYgL")
    static let manilaSunsetWalk = HavraBatikGlyphs.unfold("igmAaWg8e_/Bg3i+fe")
    static let cebuShoreBreeze = HavraBatikGlyphs.unfold("i=mBa0gFeB/asDvXg2+NxPmqlM")
    static let baliCafeTone = HavraBatikGlyphs.unfold("i7mDa-gme9/ywle3bspO")
    static let mekongFerryCrossing = HavraBatikGlyphs.unfold("v=iwdBeVo4/lmVpK4H")
    static let saigonMorningCart = HavraBatikGlyphs.unfold("fkoKnZtx/qweo3flfh")
    static let jakartaRainLane = HavraBatikGlyphs.unfold("fAoKnotv/Iw-oWfhfx26")
    static let phuketPierMorning = HavraBatikGlyphs.unfold("f1oVn9tY/KtCtofY")
    static let chiangMaiNightWalk = HavraBatikGlyphs.unfold("aYp5pZl2iaceabtbikoCna/JoUcxtKeotw-HswtQr2eVa-mJ")
    static let luangPrabangAlley = HavraBatikGlyphs.unfold("uUtgf0-98x")
    static let vientianeRiverEdge = HavraBatikGlyphs.unfold("HpabvSrya0 3Aft6l9aQsd")
    static let yangonTeaCorner = HavraBatikGlyphs.unfold("HYa3vur5aQOOr7c-hWaEr8ddR0encFeSihpqt1ATrNrZiZv2eidY")
}
